name: Deploy Playwright Analytics to GitHub Pages

on:
  workflow_run:
    workflows: ["Playwright CI"]       #This workflow will be triggered when the "Playwright CI" workflow is completed.
    types: [completed]

  workflow_dispatch:

permissions:
  contents: write                   #allows the workflow to commit and push historical Playwright results to the repository.   
  actions: read                     #allows the workflow to download artifacts from the Playwright CI workflow.
  pages: write                      #allows the workflow to deploy the GitHub Pages site.
  id-token: write                   #allows the workflow to authenticate the GitHub Pages deployment.

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:                
    # yaml folded block scalar syntax (>) is used to write multi-line strings in a more readable way.    
    # github.event_name == 'workflow_dispatch' means if this deploy-pages was triggered manually OR schedule or workflow_dispatch simply mean if it came passed down from playwright-ci workflow run.
    # github.even_name doesn't make sense right now and will result to error when this workflow is triggered manually because most logic here rely's on playwright-ci workflow run event.
    if: >                                                           
      github.event_name == 'workflow_dispatch' ||                   
      (
        github.event.workflow_run.event == 'push' ||
        github.event.workflow_run.event == 'schedule' ||
        github.event.workflow_run.event == 'workflow_dispatch'
      )
                                                                  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: playwright-analytics

      - name: Download Playwright JSON
        uses: actions/download-artifact@v4                                      # download an artifact
        with:
          name: playwright-json-${{ github.event.workflow_run.run_number }}     # download the artifact that was uploaded by Playwright CI workflow. This is the exact name of the artifact after running in github actions
          path: ./data                                                          # uploads the artifact to the github runner's ./data folder. We cannot see the artifact in our local repo because it is only available in the github runner's file system.                                         
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}                                  #specify the repository to pinpoint the name of the artifact to download. 
          run-id: ${{ github.event.workflow_run.id }}                           #specify the run-id to pinpoint the artifact from the specific Playwright CI run that triggered this deploy-pages workflow.
      
      - name: Parse Playwright results
        run: node scripts/generate-playwright-analytics.js    
        env:
          PLAYWRIGHT_RUN_ID: ${{ github.event.workflow_run.id }}
          PLAYWRIGHT_RUN_NUMBER: ${{ github.event.workflow_run.run_number }}
          PLAYWRIGHT_BRANCH: ${{ github.event.workflow_run.head_branch }}
          PLAYWRIGHT_TRIGGER: ${{ github.event.workflow_run.event }}
          
      - name: Save historical result
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add playwright_results/ docs/data.js
          git commit -m "Add Playwright run ${{ github.event.workflow_run.run_number }}" || echo "No changes to commit"
          git push origin playwright-analytics

      - name: Setup Pages       
        uses: actions/configure-pages@v5                #"I'm preparing something that will be deployed using GitHub Pages."

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3          #"Take everything inside my docs folder and package it as the website that GitHub Pages will deploy."
        with:
          path: ./docs

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}      #deploy the website to the github-pages environment and set the url of the environment to the page_url output of the deployment step.  
    runs-on: ubuntu-latest
    needs: build            
    steps:
      - name: Deploy to GitHub Pages
        id: deployment                                  #this references steps.deployment.outputs.page_url in the environment.url above.
        uses: actions/deploy-pages@v5                   #this is an official GitHub Action designed specifically to deploy a Pages artifact to GitHub Pages.