name: Deploy Playwright Analytics to GitHub Pages

on:
  workflow_run:
    workflows: ["Playwright CI"]       #This workflow will be triggered when the "Playwright CI" workflow is completed.
    types: [completed]

  workflow_dispatch:

permissions:
  contents: read                    #allows us to read the contents of the repository, which is necessary for deploying to GitHub Pages.   
  actions: read                     #allows us to read the artifacts that were uploaded by the Playwright CI workflow.
  pages: write                      #allows us to deploy to GitHub Pages
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:                
    #yaml folded block scalar syntax (>) is used to write multi-line strings in a more readable way.    
    #  github.event_name == 'workflow_dispatch' means if this deploy-pages was triggered mannually OR schedule or workflow_dispatch simply mean if it came passed down from playwright-ci workflow run.
    if: >                                                           
      github.event_name == 'workflow_dispatch' ||                   
      (
        github.event.workflow_run.event == 'schedule' ||
        github.event.workflow_run.event == 'workflow_dispatch'
      )
                                                                  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: playwright-analytics

      - name: Download Playwright JSON
        uses: actions/download-artifact@v4                                      # download an artifact
        with:
          name: playwright-json-${{ github.event.workflow_run.run_number }}     # download the artifact that was uploaded by Playwright CI workflow. This is the exact name of the artifact after running in github actions
          path: ./data                                                          # dump the artifact into a folder called data in the root of the repository and branch specified above (playwright-analytics).
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}                                  #specify the repository to pinpoint the name of the artifact to download. 
          run-id: ${{ github.event.workflow_run.id }}                           #specify the run-id (run number) to pinpoint the name of the artifact to download. This is the run number of the Playwright CI workflow that triggered this deploy-pages workflow.

      - name: Setup Pages       
        uses: actions/configure-pages@v5                #"I'm preparing something that will be deployed using GitHub Pages."

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3          #"Take everything inside my docs folder and package it as the website that GitHub Pages will deploy."
        with:
          path: ./docs

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}      #deploy the website to the github-pages environment and set the url of the environment to the page_url output of the deployment step.  
    runs-on: ubuntu-latest
    needs: build            
    steps:
      - name: Deploy to GitHub Pages
        id: deployment                                  #this references steps.deployment.outputs.page_url in the environment.url above.
        uses: actions/deploy-pages@v5                   #this is an official GitHub Action designed specifically to deploy a Pages artifact to GitHub Pages.